### ISSUE TITLE
NFS not working

### ISSUE THREAD

**Issue by DWH-WFC** [rmrector/script.artwork.dump#10]
Hello from Germany.

I've been using your addon for quite a long time, I just noticed that it hasn't worked in connection with my NAS (NFS share) lately.

Version 2.2 working fine

Maybe it's possible to fix it.
Thanks in advance 

```
2022-03-07 16:36:08.773 T:20164   ERROR <general>: CGUIMediaWindow::GetDirectory(nfs://192.168.0.40/volume1/Kodi/library/Movies/Ghostbusters - Die Geisterjäger (1984)/Ghostbusters - Die Geisterjäger (1984).strm) failed
2022-03-07 16:36:13.492 T:7340  WARNING <general>: [script.artwork.dump] Artwork caching requires Kodi setting 'Allow remote control via HTTP' enabled
2022-03-07 16:36:13.496 T:7340    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'MediaItem' object has no attribute 'encode'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\bunny\AppData\Roaming\Kodi\addons\script.artwork.dump\python\service.py", line 214, in <module>
                                                       ArtworkService().run()
                                                     File "C:\Users\bunny\AppData\Roaming\Kodi\addons\script.artwork.dump\python\service.py", line 137, in run
                                                       successful = self.process_allvideos(self.processed.does_not_exist)
                                                     File "C:\Users\bunny\AppData\Roaming\Kodi\addons\script.artwork.dump\python\service.py", line 152, in process_allvideos
                                                       return self._process_mediatypes(mediatypes.videotypes, shouldinclude_fn)
                                                     File "C:\Users\bunny\AppData\Roaming\Kodi\addons\script.artwork.dump\python\service.py", line 176, in _process_mediatypes
                                                       result = self.processor.process_list_with_total(flatten_to_mediaitems(), totalcount)
                                                     File "C:\Users\bunny\AppData\Roaming\Kodi\addons\script.artwork.dump\python\artworkprocessor.py", line 71, in process_list_with_total
                                                       aborted, artcount = self._process_list(medialist)
                                                     File "C:\Users\bunny\AppData\Roaming\Kodi\addons\script.artwork.dump\python\artworkprocessor.py", line 83, in _process_list
                                                       self.progressdisplay.update_progress(mediaitem.label if not exclude else mediaitem)
                                                     File "C:\Users\bunny\AppData\Roaming\Kodi\addons\script.artwork.dump\python\artworkprocessor.py", line 180, in update_progress
                                                       if not check_utf8(message):
                                                     File "C:\Users\bunny\AppData\Roaming\Kodi\addons\script.artwork.dump\python\libs\pykodi.py", line 94, in check_utf8
                                                       string.encode('utf-8')
                                                   AttributeError: 'MediaItem' object has no attribute 'encode'
                                                   -->End of Python script error report<--
                                                   
2022-03-07 16:36:13.779 T:4644     INFO <general>: initializing python engine.
```

**Comment by rmrector** [comment]
Fixed in 0.2.4. Thanks for the report.
