### ISSUE TITLE
Getting an error and stops

### ISSUE THREAD

**Issue by papampi** [rmrector/script.artwork.dump#7]
Its giving me this error and stops 
Ubuntu 21.04
Kodi 19.1

```
2021-07-13 14:55:57.360 T:133391   DEBUG <general>: GetSongsByWhereJSON - query took 4 ms
2021-07-13 14:55:57.360 T:133391   DEBUG <general>: connect replacing configured host 192.168.1.251 with resolved host 192.168.1.251
2021-07-13 14:55:57.382 T:133391   DEBUG <general>: [script.artwork.dump] Processing album 'Keith Jarrett - Mysteries/Shades' automatically.
2021-07-13 14:55:57.675 T:133361   DEBUG <general>: Sink changed
2021-07-13 14:55:58.066 T:133391   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SystemError'>
                                                   Error Contents: ../Objects/dictobject.c:1464: bad argument to internal function
                                                   Traceback (most recent call last):
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/service.py", line 209, in <module>
                                                       ArtworkService().run()
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/service.py", line 143, in run
                                                       successful = self.process_allmusic(self.processed.does_not_exist)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/service.py", line 156, in process_allmusic
                                                       return self._process_mediatypes(mediatypes.audiotypes, shouldinclude_fn)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/service.py", line 171, in _process_mediatypes
                                                       result = self.processor.process_list_with_total(flatten_to_mediaitems(), totalcount)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/artworkprocessor.py", line 70, in process_list_with_total
                                                       aborted, artcount = self._process_list(medialist)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/artworkprocessor.py", line 90, in _process_list
                                                       services_hit = self._process_item(mediaitem)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/artworkprocessor.py", line 124, in _process_item
                                                       services_hit, error = self.downloader.downloadfor(mediaitem)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/filemanager.py", line 82, in downloadfor
                                                       result, err = self.doget(url)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/filemanager.py", line 119, in doget
                                                       result = self.getter(url, **kwargs)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/libs/webhelper.py", line 26, in __call__
                                                       return self._inner_call(url, **kwargs)
                                                     File "/home/payam/.kodi/addons/script.artwork.dump/python/libs/webhelper.py", line 34, in _inner_call
                                                       result = self.session.get(url, **kwargs)
                                                     File "/home/payam/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 555, in get
                                                       return self.request('GET', url, **kwargs)
                                                     File "/home/payam/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/payam/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/payam/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "/home/payam/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 696, in urlopen
                                                       self._prepare_proxy(conn)
                                                     File "/home/payam/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 964, in _prepare_proxy
                                                       conn.connect()
                                                     File "/home/payam/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 411, in connect
                                                       self.sock = ssl_wrap_socket(
                                                     File "/home/payam/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                     File "/home/payam/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                     File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "/usr/lib/python3.9/ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   SystemError: ../Objects/dictobject.c:1464: bad argument to internal function
                                                   -->End of Python script error report<--
                                                   
2021-07-13 14:55:58.066 T:133391   DEBUG <general>: onExecutionDone(0, /home/payam/.kodi/addons/script.artwork.dump/python/service.py)
2021-07-13 14:55:58.068 T:133358   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-07-13 14:55:58.069 T:133361   DEBUG <general>: Sink changed
2021-07-13 14:55:58.079 T:133391   DEBUG <general>: .
2021-07-13 14:55:58.106 T:133391    INFO <general>: Python interpreter stopped
2021-07-13 14:55:58.106 T:133391   DEBUG <general>: Thread LanguageInvoker 140119315035712 terminating
2021-07-13 14:55:58.281 T:133358   DEBUG <general>: ------ Window Deinit (DialogExtendedProgressBar.xml) ------
2021-07-13 14:56:03.779 T:133358   DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------
2021-07-13 14:56:06.915 T:133384   DEBUG <general>: Thread JobWorker 140119647888960 terminating (autodelete)
2021-07-13 14:56:59.003 T:133358    INFO <general>: Samba is idle. Closing the remaining connections
2021-07-13 14:57:03.991 T:133361   DEBUG <general>: Sink changed

```

**Comment by papampi** [comment]
Tried multiple times, it stops on the same album everytime.
Keith Jarrett - Mysteries/Shades

**Comment by papampi** [comment]
So the only way to resolve the issue and run the addon was to remove the album ...

**Comment by rmrector** [comment]
That is an error way down deep, it will need further investigation.
