### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by croneter** [rmrector/script.artwork.dump#9]
This renders the add-on completely unusable for me, unfortunately 😞 

```
2021-07-24 10:49:20.521 T:31034   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ZeroDivisionError'>
                                                   Error Contents: integer division or modulo by zero
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.artwork.dump/python/service.py", line 209, in <module>
                                                       ArtworkService().run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.artwork.dump/python/service.py", line 137, in run
                                                       successful = self.process_allvideos(self.processed.does_not_exist)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.artwork.dump/python/service.py", line 152, in process_allvideos
                                                       return self._process_mediatypes(mediatypes.videotypes, shouldinclude_fn)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.artwork.dump/python/service.py", line 171, in _process_mediatypes
                                                       result = self.processor.process_list_with_total(flatten_to_mediaitems(), totalcount)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.artwork.dump/python/artworkprocessor.py", line 70, in process_list_with_total
                                                       aborted, artcount = self._process_list(medialist)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.artwork.dump/python/artworkprocessor.py", line 82, in _process_list
                                                       self.progressdisplay.update_progress(mediaitem.label if not exclude else None)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.artwork.dump/python/artworkprocessor.py", line 179, in update_progress
                                                       self.currentcount * 100 // self.totalcount
                                                   ZeroDivisionError: integer division or modulo by zero
                                                   -->End of Python script error report<--
```
Full log: 
[kodi.old.log](https://github.com/rmrector/script.artwork.dump/files/6872161/kodi.old.log)

**Comment by rmrector** [comment]
Fixed in version 0.2.2.
